; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 2
; RUN: llc -mtriple=riscv64-codasip-linux-gnu -mattr=+zcheripurecap,+cap-mode -target-abi l64pc128d  %s -o - | FileCheck %s
target datalayout = "e-m:e-pf200:128:128:128:64-p:64:64-i64:64-i128:128-n32:64-S128-A200-P200-G200"
target triple = "riscv64-codasip-linux-musl"

@.str = private unnamed_addr addrspace(200) constant [31 x i8] c"DHRYSTONE PROGRAM, 1'ST STRING\00", align 1

define dso_local zeroext i8 @foo(i64 noundef %i) addrspace(200) {
; CHECK-LABEL: foo:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    caddi csp, csp, -64
; CHECK-NEXT:    .cfi_def_cfa_offset 64
; CHECK-NEXT:    li a1, 50
; CHECK-NEXT:    caddi ca2, csp, 8
; CHECK-NEXT:    lui a3, 4
; CHECK-NEXT:    lui a4, 300325
; CHECK-NEXT:    scbndsr ca1, ca2, a1
; CHECK-NEXT:  .LBB0_1: # %entry
; CHECK-NEXT:    # Label of block must be emitted
; CHECK-NEXT:    auipc ca2, %pcrel_hi(.LCPI0_0)
; CHECK-NEXT:    caddi ca2, ca2, %pcrel_lo(.LBB0_1)
; CHECK-NEXT:    addiw a3, a3, 1870
; CHECK-NEXT:    sh a3, 28(ca1)
; CHECK-NEXT:  .LBB0_2: # %entry
; CHECK-NEXT:    # Label of block must be emitted
; CHECK-NEXT:    auipc ca3, %pcrel_hi(.LCPI0_1)
; CHECK-NEXT:    caddi ca3, ca3, %pcrel_lo(.LBB0_2)
; CHECK-NEXT:    addiw a4, a4, 1107
; CHECK-NEXT:    ld a2, 0(ca2)
; CHECK-NEXT:    ld a3, 0(ca3)
; CHECK-NEXT:    sw a4, 24(ca1)
; CHECK-NEXT:  .LBB0_3: # %entry
; CHECK-NEXT:    # Label of block must be emitted
; CHECK-NEXT:    auipc ca4, %pcrel_hi(.LCPI0_2)
; CHECK-NEXT:    caddi ca4, ca4, %pcrel_lo(.LBB0_3)
; CHECK-NEXT:    ld a4, 0(ca4)
; CHECK-NEXT:    sd a2, 16(ca1)
; CHECK-NEXT:    sd a3, 8(ca1)
; CHECK-NEXT:    sb zero, 30(ca1)
; CHECK-NEXT:    sd a4, 0(ca1)
; CHECK-NEXT:    cadd ca0, ca1, a0
; CHECK-NEXT:    lbu a0, 0(ca0)
; CHECK-NEXT:    caddi csp, csp, 64
; CHECK-NEXT:    .cfi_def_cfa_offset 0
; CHECK-NEXT:    ret
entry:
  %s2 = alloca [50 x i8], align 1, addrspace(200)
  call void @llvm.memcpy.p200.p200.i64(ptr addrspace(200) noundef nonnull align 1 dereferenceable(31) %s2, ptr addrspace(200) noundef nonnull align 1 dereferenceable(31) @.str, i64 31, i1 false) #1
  %arrayidx = getelementptr inbounds [50 x i8], ptr addrspace(200) %s2, i64 0, i64 %i
  %0 = load i8, ptr addrspace(200) %arrayidx, align 1
  ret i8 %0
}

declare void @llvm.memcpy.p200.p200.i64(ptr addrspace(200) noalias nocapture writeonly, ptr addrspace(200) noalias nocapture readonly, i64, i1 immarg) addrspace(200)

attributes #1 = { no_preserve_cheri_tags nounwind }

